# Fake DB
### Extract and Data Preparation
+ Repo: https://sgithub.fr.world.socgen/oborderi/bot-ca

In [1]:
! which jupyter

/home/pmarion/anaconda3/bin/jupyter

In [2]:
import sys
sys.executable

'/home/pmarion/anaconda3/envs/bot-ca/bin/python'

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
from IPython.display import display
import os

from corp_actions.db_analysis.db import DB

INFO:root:InitApp

In [5]:
db = DB(random=True)

In [6]:
db.get_random()

creating df merger_acquisition
creating df buy_back

In [7]:
db.buy_back

,creation_date,data_bool2,data_bool_buy_back,data_categorical_buy_back,data_date_buy_back,data_num_buy_back,geographic,index,sector
0,2010-10-08 11:55:27.095031,None,True,rixqgck,2012-11-04 23:54:42.640397,5.207121,Italy,Index6,Banking
1,2010-07-29 02:04:51.237721,True,True,scqhy,2012-07-14 22:38:34.975458,5.628147,USA,Index1,Strategy
2,2011-02-08 05:13:46.462810,None,True,to,2014-03-30 23:58:40.818783,7.033050,GB,Index6,Strategy
3,2014-09-21 22:12:12.701919,True,True,bg,2012-07-20 23:33:16.894062,9.957742,None,None,Taxi_driving
4,2012-03-10 17:52:14.135887,False,True,ijlbarca,2011-05-05 08:52:46.780571,5.783748,Italy,Index3,Banking
5,2011-09-06 02:20:05.288272,True,True,rixqgck,2011-05-08 03:52:17.761875,2.557691,GB,Index2,None
6,2014-02-17 21:33:43.949236,True,False,scqhy,2012-12-23 13:15:06.141482,7.473950,USA,Index1,Taxi_driving
7,2014-07-18 15:46:22.924332,None,False,to,2013-10-06 21:00:14.963857,3.730040,France,Index5,Industry
8,2011-11-13 22:28:10.989773,True,True,bg,2015-06-07 10:06:56.308131,1.438252,GB,Index3,Industry
9,2010-07-24 05:53:15.564580,True,False,ijlbarca,2011-10-02 05:12:41.109223,0.166214,Germany,Index1,Industry
10,2014-02-18 08:24:45.075788,False,True,rixqgck,2011-04-10 10:17:57.453275,7.560789,France,None,None
11,2014-09-18 06:48:16.743742,True,False,scqhy,2014-05-08 15:37:40.964592,7.751485,None,Index1,Taxi_driving
12,2015-04-20 04:14:15.418875,True,False,to,2011-07-14 23:33:06.273957,9.943888,Germany,Index6,None
13,2010-11-13 00:34:25.818031,True,False,bg,2013-04-04 01:36:04.006400,9.050735,Italy,Index4,Farming
14,2010-06-03 02:44:35.343459,True,None,ijlbarca,2013-09-29 22:37:38.396215,9.101677,Italy,Index6,Industry
15,2014-02-09 03:47:36.285543,False,False,rixqgck,2012-05-13 22:59:59.802959,7.864674,Spain,Index6,Strategy
16,2012-11-04 02:28:09.888629,True,None,scqhy,2013-09-17 06:21:19.359729,5.907152,Spain,Index3,Taxi_driving
17,2013-12-28 16:42:35.610582,False,False,to,2011-03-12 10:05:54.496497,9.858726,None,Index3,Farming
18,2012-10-15 01:49:53.446986,None,False,bg,2012-04-13 17:21:15.633006,1.639063,Germany,Index3,Industry
19,2011-08-30 17:31:08.920208,False,False,ijlbarca,2014-09-29 05:19:39.056307,7.658189,GB,Index2,CS
20,2014-02-14 17:10:05.540483,False,True,rixqgck,2013-08-17 02:35:11.660711,0.712979,Germany,Index5,Industry
21,2014-08-28 21:44:42.568468,None,True,scqhy,2012-09-09 14:27:46.169678,7.393897,GB,Index2,CS
22,2011-12-13 06:52:13.561912,True,False,to,2012-05-06 13:41:14.563232,2.889615,Spain,Index1,Strategy
23,2011-01-24 09:18:44.477329,True,True,bg,2011-01-24 22:16:49.377729,3.636241,None,Index4,None
24,2010-01-29 02:10:59.539597,False,True,ijlbarca,2012-10-22 12:47:06.397525,1.213527,None,Index3,Taxi_driving
25,2014-12-30 06:08:07.824341,True,False,rixqgck,2013-11-20 00:14:52.404990,8.397344,Spain,None,Strategy
26,2011-06-02 05:57:36.978193,None,False,scqhy,2014-09-24 20:22:14.612505,7.064077,None,Index4,CS
27,2010-09-26 01:00:29.842444,False,True,to,2010-11-11 03:22:24.067885,5.556692,Germany,Index2,CS
28,2014-06-16 09:32:12.177769,False,True,bg,2015-05-11 08:31:51.145458,2.816458,Italy,Index1,Farming
29,2011-09-29 12:03:15.250719,True,False,ijlbarca,2010-06-05 06:46:23.578082,4.248405,Italy,Index6,CS
30,2012-05-14 10:24:54.995158,True,False,rixqgck,2012-09-04 01:14:08.564446,9.161730,France,Index6,Strategy
31,2012-05-06 13:54:41.269358,False,True,scqhy,2015-02-06 10:36:53.949147,2.681197,Italy,None,Industry
32,2014-12-15 09:30:30.189972,False,False,to,2010-03-31 11:50:37.235148,8.542143,Italy,Index3,CS
33,2012-03-29 17:16:12.363102,True,None,bg,2010-06-25 04:40:59.943164,4.605076,GB,Index1,None
34,2014-10-04 14:54:17.248269,True,True,ijlbarca,2012-02-09 14:52:51.711696,0.719361,None,Index1,CS
35,2015-03-16 08:08:57.094077,False,False,rixqgck,2013-03-12 10:14:10.923027,3.016552,None,None,Taxi_driving
36,2012-07-11 04:16:01.300095,None,True,scqhy,2012-03-06 04:38:39.214615,8.552395,Germany,Index1,Farming
37,2011-09-29 05:02:54.263757,False,False,to,2015-02-01 04:31:15.500276,1.247550,Germany,Index2,CS
38,2014-12-25 04:29:55.424023,None,True,bg,2011-03-31 20:18:01.611811,1.030818,France,Index5,Banking
39,2012-09-29 11:57:58.911624,False,True,ijlbarca,2011-06-09 16:45:48.081100,3.070492,Spain,Index3,Banking
40,2011-08-30 01:56:03.613921,False,True,rixqgck,2011-08-05 20:07:08.192219,0.632946,Germany,None,None
41,2011-12-11 10:38:55.769272,None,False,scqhy,2012-11-12 14:21:25.934847,9.100666,Spain,Index6,CS
42,2011-07-22 00:22:35.543861,False,False,to,2011-08-31 18:21:37.773440,3.605251,France,Index1,CS
43,2011-11-27 13:25:01.601834,None,False,bg,2011-11-03 23:42:36.752195,4.568029,Spain,Index1,Industry
44,2014-05-19 01:19:22.287465,True,True,ijlbarca,2013-06-14 00:54:05.163699,9.002579,Italy,Index4,Strategy
45,2013-01-15 18:25:48.029258,True,True,rixqgck,2013-05-10 11:06:35.763426,7.529220,Spain,Index2,Farming
46,2010-05-22 13:01:33.000218,True,True,scqhy,2012-09-27 04:05:52.255163,4.142326,USA,Index4,CS
47,2014-12-08 03:13:33.097887,False,False,to,2012-07-07 07:44:04.577932,9.863616,France,Index3,None
48,2011-08-02 17:21:11.579842,False,True,bg,2014-02-17 03:48:30.363807,6.342547,Italy,Index3,Farming
49,2011-09-11 06:37:04.514589,True,True,ijlbarca,2010-11-23 14:18:58.186120,8.246424,Germany,None,None

In [8]:
db.merger_acquisition

,creation_date,data_bool2,data_bool_merger_acquisition,data_categorical_merger_acquisition,data_date_merger_acquisition,data_num_merger_acquisition,geographic,index,sector
0,2015-05-05 21:29:39.027009,True,False,mlgo,2011-06-22 15:16:07.706982,7.756250,None,Index3,Farming
1,2011-11-25 21:42:42.413020,False,True,raqie,2010-07-01 20:49:57.462417,3.769570,USA,Index5,None
2,2014-04-18 13:37:13.761320,True,None,gyhud,2010-02-12 19:18:40.712605,9.836935,Germany,Index1,Industry
3,2011-03-10 21:50:19.168151,True,False,vsx,2013-11-22 22:28:00.577204,1.459500,Spain,Index2,Farming
4,2010-06-24 17:34:07.022189,True,False,mswcsjur,2013-02-06 21:53:29.250682,3.869648,Italy,Index1,Banking
5,2012-09-18 18:55:30.464556,None,True,mlgo,2013-01-31 18:52:58.943216,0.595021,Spain,Index2,Banking
6,2010-07-18 00:05:59.443416,None,True,raqie,2012-07-06 07:31:33.605557,6.441708,Germany,Index2,CS
7,2010-10-15 17:22:03.705677,False,True,gyhud,2012-11-28 05:06:57.971225,8.706804,Italy,Index5,Banking
8,2010-11-06 18:14:33.352663,False,False,vsx,2014-02-28 20:47:56.319975,4.292121,Germany,Index4,Industry
9,2013-11-09 14:21:49.925223,False,None,mswcsjur,2014-02-08 06:58:40.979877,7.713783,Italy,Index6,Taxi_driving
10,2012-10-30 11:11:39.088521,True,False,mlgo,2011-01-23 17:35:00.845699,7.067466,GB,Index5,Farming
11,2010-10-27 15:24:24.830445,False,False,raqie,2010-02-05 12:53:03.848394,2.327632,None,None,Strategy
12,2011-12-25 00:59:23.844360,True,True,gyhud,2010-12-19 16:53:09.856773,3.571087,Italy,Index1,CS
13,2012-11-09 10:16:02.200832,True,True,vsx,2014-12-19 05:23:15.901259,0.953295,USA,Index1,Industry
14,2014-03-18 22:57:12.580317,True,None,mswcsjur,2010-04-09 14:37:16.736582,4.819249,Germany,Index3,Farming
15,2011-03-16 08:58:25.289503,True,True,mlgo,2013-01-06 04:28:49.442842,5.953041,GB,Index2,Strategy
16,2010-11-03 20:16:11.420375,True,None,raqie,2012-05-19 23:44:53.315491,3.399383,Italy,Index3,Farming
17,2012-01-07 11:28:07.550819,None,True,gyhud,2012-12-11 09:55:56.758273,1.707265,Spain,None,CS
18,2013-05-18 13:22:47.063600,False,True,vsx,2011-08-03 21:51:44.489650,0.937039,USA,Index3,None
19,2013-10-21 13:21:27.629388,True,None,mswcsjur,2015-02-19 09:33:03.159107,1.283525,GB,Index3,None
20,2012-06-14 21:01:34.353482,False,True,mlgo,2012-05-09 19:17:54.679838,1.743378,USA,Index1,Farming
21,2013-08-19 09:48:48.790627,False,True,raqie,2011-11-14 08:48:25.288478,8.627402,Spain,Index5,Banking
22,2014-06-14 12:24:37.287626,False,True,gyhud,2010-06-13 12:48:20.280805,7.363417,Germany,Index6,Farming
23,2013-11-22 16:15:52.886092,None,False,vsx,2015-04-20 02:35:28.515450,7.492597,Italy,Index5,CS
24,2011-08-29 21:56:41.537987,True,False,mswcsjur,2012-11-08 15:06:47.256049,0.729693,Italy,None,CS
25,2015-05-04 13:31:30.509945,True,False,mlgo,2010-12-20 04:51:21.377846,2.229514,GB,Index6,Industry
26,2015-06-29 23:08:02.465504,False,True,raqie,2013-09-20 13:43:39.563874,9.933929,Spain,Index6,Industry
27,2010-05-08 13:55:44.696945,None,True,gyhud,2011-09-07 13:49:13.928030,2.342197,Spain,Index6,Farming
28,2013-12-02 02:33:40.182768,False,True,vsx,2015-05-22 20:14:30.057380,1.017901,France,Index4,Banking
29,2014-12-20 04:10:37.413908,True,False,mswcsjur,2012-10-19 16:24:32.794402,5.708617,France,Index1,CS
30,2013-09-17 23:01:31.224425,True,True,mlgo,2013-03-03 17:53:25.129993,2.670129,GB,Index5,Banking
31,2015-01-08 19:54:44.753829,True,False,raqie,2012-11-12 20:18:45.545935,9.146192,Germany,Index3,None
32,2013-01-18 01:16:09.625983,True,False,gyhud,2010-05-20 04:40:26.376663,1.435438,None,Index2,Strategy
33,2011-11-09 05:28:27.732032,False,True,vsx,2015-04-23 04:56:33.313263,3.468709,France,Index1,CS
34,2010-02-20 09:34:18.244342,True,True,mswcsjur,2010-08-27 22:12:01.258056,0.480738,Italy,None,None
35,2010-10-05 11:43:14.783079,False,False,mlgo,2014-07-27 03:31:14.908042,0.091201,None,Index3,Industry
36,2014-09-21 01:37:28.442137,True,True,raqie,2014-09-02 01:26:26.607328,8.976636,France,Index5,Industry
37,2014-02-08 15:18:32.956678,True,False,gyhud,2015-02-12 04:49:04.495027,0.093227,None,Index5,Taxi_driving
38,2012-01-31 13:06:07.474319,True,False,vsx,2013-10-29 14:48:49.915022,4.717003,Spain,Index1,Taxi_driving
39,2010-02-04 15:16:39.999444,True,True,mswcsjur,2013-02-14 00:42:56.252327,2.192246,France,Index3,Industry
40,2013-04-07 17:40:19.847828,True,None,mlgo,2014-12-18 09:05:11.264315,8.302180,GB,Index2,None
41,2015-04-17 13:34:17.269071,True,False,raqie,2014-01-07 05:21:29.971233,0.673427,None,Index3,Banking
42,2012-05-03 10:27:21.563798,True,False,gyhud,2013-10-23 01:21:40.094560,8.577565,France,Index6,CS
43,2010-03-13 06:36:06.062252,False,False,vsx,2014-12-31 09:18:13.477621,6.595750,USA,Index6,Farming
44,2014-05-01 00:40:20.505312,True,False,mswcsjur,2012-08-01 06:12:18.666773,1.644342,None,None,Banking
45,2011-12-09 17:48:28.954055,False,False,mlgo,2013-02-16 10:46:37.832694,6.929146,France,Index5,Farming
46,2012-03-18 11:23:49.733514,True,False,raqie,2014-04-07 00:51:17.416338,0.651852,GB,Index3,Taxi_driving
47,2011-07-31 21:43:55.575974,True,False,gyhud,2015-04-09 22:39:10.628326,6.162052,France,Index6,Taxi_driving
48,2014-08-12 17:43:58.326721,False,False,vsx,2015-05-06 19:17:57.119001,0.832546,France,Index3,Farming
49,2015-02-13 01:55:29.985404,None,True,mswcsjur,2010-09-30 17:39:26.198730,0.433348,France,Index2,Strategy

In [9]:
db.put_to_disk(os.path.join('data', 'carbon_random3.pk'))

store tables from disk
	table merger_acquisition
	table buy_back

In [10]:
db.get_from_disk(os.path.join('data', 'carbon_random3.pk'))

read tables from disk
	table merger_acquisition
	table buy_back

In [11]:
db.put_to_csv()

save dataframes to disk
	merger_acquisition       	dump/df_merger_acquisition.csv
	buy_back                 	dump/df_buy_back.csv

In [12]:
# print(db.overview(toString=True))
db.overview()

Overview - dataframes structures

merger_acquisition
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
creation_date                          50 non-null datetime64[ns]
data_bool2                             44 non-null object
data_bool_merger_acquisition           44 non-null object
data_categorical_merger_acquisition    50 non-null object
data_date_merger_acquisition           50 non-null datetime64[ns]
data_num_merger_acquisition            50 non-null float64
geographic                             43 non-null object
index                                  45 non-null object
sector                                 44 non-null object
dtypes: datetime64[ns](2), float64(1), object(6)
memory usage: 3.6+ KB

buy_back
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
creation_date                50 non-null datetime64[ns]
data_bool2                   40 non-null object
data_bool_buy_back           47 non-null object
data_categorical_buy_back    50 non-null object
data_date_buy_back           50 non-null datetime64[ns]
data_num_buy_back            50 non-null float64
geographic                   42 non-null object
index                        43 non-null object
sector                       42 non-null object
dtypes: datetime64[ns](2), float64(1), object(6)
memory usage: 3.6+ KB

In [13]:
db.distinct_values()

merger_acquisition
	 number columns: ['data_num_merger_acquisition']
	 date columns: ['creation_date', 'data_date_merger_acquisition']
buy_back
	 number columns: ['data_num_buy_back']
	 date columns: ['creation_date', 'data_date_buy_back']

Overview - distinct values
{
  "merger_acquisition": {
    "creation_date": {
      "type": "date",
      "earliest": "2010-02-04",
      "latest": "2015-06-29"
    },
    "data_bool2": [
      false,
      true,
      null
    ],
    "data_bool_merger_acquisition": [
      false,
      true,
      null
    ],
    "data_categorical_merger_acquisition": [
      "gyhud",
      "vsx",
      "mswcsjur",
      "raqie",
      "mlgo"
    ],
    "data_date_merger_acquisition": {
      "type": "date",
      "earliest": "2010-02-05",
      "latest": "2015-05-22"
    },
    "data_num_merger_acquisition": {
      "type": "number",
      "min": 0.09120091429748789,
      "max": 9.93392944388057,
      "avg": 4.154453922581386
    },
    "geographic": [
      "USA",
      "Spain",
      "Italy",
      null,
      "France",
      "Germany",
      "GB"
    ],
    "index": [
      "Index1",
      "Index3",
      "Index2",
      "Index5",
      null,
      "Index4",
      "Index6"
    ],
    "sector": [
      "Taxi_driving",
      "Farming",
      "CS",
      null,
      "Banking",
      "Strategy",
      "Industry"
    ]
  },
  "buy_back": {
    "creation_date": {
      "type": "date",
      "earliest": "2010-01-29",
      "latest": "2015-04-20"
    },
    "data_bool2": [
      false,
      true,
      null
    ],
    "data_bool_buy_back": [
      false,
      true,
      null
    ],
    "data_categorical_buy_back": [
      "bg",
      "to",
      "ijlbarca",
      "rixqgck",
      "scqhy"
    ],
    "data_date_buy_back": {
      "type": "date",
      "earliest": "2010-03-31",
      "latest": "2015-06-07"
    },
    "data_num_buy_back": {
      "type": "number",
      "min": 0.16621350145090918,
      "max": 9.957741601997617,
      "avg": 5.498049649577365
    },
    "geographic": [
      "USA",
      "Spain",
      "Italy",
      null,
      "France",
      "Germany",
      "GB"
    ],
    "index": [
      "Index1",
      "Index3",
      "Index2",
      null,
      "Index5",
      "Index4",
      "Index6"
    ],
    "sector": [
      "Taxi_driving",
      "Farming",
      "CS",
      null,
      "Banking",
      "Strategy",
      "Industry"
    ]
  }
}